# parameters 
gravity_acceleration: 9.81 # m/s^2

# setting of parabolic dataset
num_samples: 500  
num_points:  100  

# The range of initial velocity and angle
initial_velocity_min: 10.0  # m/s
initial_velocity_max: 30.0  # m/s
angle_min: 30.0  # degrees
angle_max: 60.0  # degrees

# Training, validation, and test dataset ratio
train_ratio: 0.7
val_ratio: 0.2
test_ratio: 0.1

# Random state for splitting the dataset
random_state: 42

# Model trining parameters
training:
  epoch_max: 1000
  learning_rate: 1e-3
  target_loss: 1e-2
  hidden_size: 128